### ISSUE TITLE
"Reserved Names" are Ignored When "Rename Globals" is Enabled

### ISSUE THREAD

**Issue by imallett** [javascript-obfuscator/javascript-obfuscator-ui#27]
E.g. given the following code:
    `var do_not_rename = 1;`
And adding to "Reserved Names":
    `^do_not_rename`
The output is:
    `var c=0x1;`
I would expect the variable not to be renamed.

**Comment by Enuratique** [comment]
I'm also experiencing this bug. Super annoying.

**Comment by sanex3339** [comment]
Should be fixed few releases ago

**Comment by iceman2894** [comment]
Still happening for me **@2.10.1**

**CLI**
`--rename-globals
true
--reserved-names
'a'
--reserved-strings
'a'`

**file.js**
`var a;`

**file.min.js**
`var a0_0x2ffb6f;`


**NPM**
`$ npm list -g | grep javascript
-- javascript-obfuscator@2.10.1
  +-- @javascript-obfuscator/escodegen@2.1.1
`
